version: '2'
services:
  db:
   image: postgres:9.6.11-alpine
   container_name: postgres_sonarqube
   networks:
    - sonarqubenet
   environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

  adminer:
    image: adminer
    restart: always
    networks:
      - sonarqubenet
    ports:
       - 19090:8080
  sonarqube:
    image: sonarqube:7.4-community-alpine
    container_name: sonarqube
    networks:
      - sonarqubenet
    links:
      - db:db
    ports:
      - "9090:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /etc/localtime:/etc/localtime:ro
networks:
  sonarqubenet:
    driver: bridge
