version: '3'

services:
  db:
    image: mysql:5.7.23
    restart: always
    container_name: "mysql_jms"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: jumpserver
      MYSQL_USER: jumpserver
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - /data/jumpserver-data/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - "jumpservernet"
  redis:
    image: redis:3
    container_name: "redis_jms"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /data/jumpserver-data/redis:/data
    networks:
      - "jumpservernet"
  jumpserver:
    image: wojiushixiaobai/jumpserver:1.4.3
    container_name: "jms_v1.4.3"
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DB_ENGINE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: jumpserver
      DB_PASSWORD: 123456
      DB_NAME: jumpserver
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8080:80
      - 2222:2222
    volumes:
      - /data/jumpserver-data/jms_data/jms:/opt/jumpserver/data
      - /data/jumpserver-data/jms_data/coco_keys:/opt/coco/keys
      - /data/jumpserver-data/jms_data/guacamole:/config/guacamole/keys
      - /data/jumpserver-data/jms_data/mysql:/var/lib/mysql
    networks:
      - "jumpservernet"

networks:
  jumpservernet:
    driver: bridge
